imerir_creation_client:
    path:     /contacts/creation
    defaults: { _controller: ImerirContactBundle:Default:ajoutContact }

imerir_validation_creation_client:
    path:     /contacts/creation/validation
    defaults: { _controller: ImerirContactBundle:Default:execAjoutContact }

imerir_modification_client:
    path:     /contacts/modification
    defaults: { _controller: ImerirContactBundle:Default:modifContact }

imerir_validation_modification_client:
    path:     /contacts/modification/validation
    defaults: { _controller: ImerirContactBundle:Default:execModifContact }

imerir_stats_client_sms_mail:
    path: /contacts/stats/sms_mail
    defaults: { _controller: ImerirContactBundle:Stats:index }

imerir_stats_client_age:
    path: /contacts/stats/age
    defaults: { _controller: ImerirContactBundle:Stats:contactAges }

imerir_stats_client_ville:
    path: /contacts/stats/ville
    defaults: { _controller: ImerirContactBundle:Stats:contactVilles }