imerir_creation_fournisseur:
    path:     /fournisseurs/creation
    defaults: { _controller: ImerirFournisseurBundle:Default:ajoutFournisseur }

imerir_validation_creation_fournisseur:
    path:     /fournisseurs/creation/validation
    defaults: { _controller: ImerirFournisseurBundle:Default:execAjoutFournisseur }

imerir_validation_modification_fournisseur:
    path:     /fournisseurs/modification/validation
    defaults: { _controller: ImerirFournisseurBundle:Default:execModifFournisseur }

imerir_modification_fournisseur:
    path:     /fournisseurs/modification
    defaults: { _controller: ImerirFournisseurBundle:Default:modifFournisseur }

imerir_creation_commande_fournisseur:
    path: /fournisseurs/commandes/creation
    defaults: { _controller: ImerirFournisseurBundle:Commandes:ajoutCommande }

imerir_creation_validation_commande_fournisseur:
    path: /fournisseurs/commandes/creation/validation
    defaults: { _controller: ImerirFournisseurBundle:Commandes:execAjoutCommande }

imerir_modification_commande_fournisseur:
    path: /fournisseurs/commandes/modification
    defaults: { _controller: ImerirFournisseurBundle:Commandes:modifCommande }

imerir_modification_validation_commande_fournisseur:
    path: /fournisseurs/commandes/modification/validation
    defaults: { _controller: ImerirFournisseurBundle:Commandes:execModifCommande }

imerir_historique_commande_fournisseur:
    path: /fournisseurs/commandes/historique
    defaults: { _controller: ImerirFournisseurBundle:Commandes:historiqueCommande }
    
imerir_suppression_fournisseur:
    path: /fournisseurs/suppression
    defaults: { _controller: ImerirFournisseurBundle:Default:execSupprFournisseur }
    
imerir_suppression_commande_fournisseur:
    path: /fournisseurs/commandes/suppression
    defaults: { _controller: ImerirFournisseurBundle:Commandes:execSupprCommande }        