imerir_noyau_homepage:
    path:     /login/
    defaults: { _controller: ImerirNoyauBundle:Default:authentification }
    
imerir_noyau_caisse:
    path:     /
    defaults: { _controller: ImerirNoyauBundle:Caisse:Caisse }
    
imerir_noyau_ajax_getPrixFromCodeBarre_caisse:
    path:     /ajax/getPrixFromCodeBarre
    defaults: { _controller: ImerirNoyauBundle:AjaxCaisse:getPrixFromCodeBarre }
    
imerir_noyau_check:
    path:     /check_login/
    defaults: { _controller: ImerirNoyauBundle:Default:checkLogin }