imerir_noyau_homepage:
    path:     /login/
    defaults: { _controller: ImerirNoyauBundle:Default:authentification }
    
imerir_noyau_caisse:
    path:     /
    defaults: { _controller: ImerirNoyauBundle:Caisse:caisse }

imerir_noyau_ajax_getPrixFromCodeBarre_caisse:
    path:     /ajax/getPrixFromCodeBarre
    defaults: { _controller: ImerirNoyauBundle:AjaxCaisse:getPrixFromCodeBarre }
    
imerir_noyau_ajax_getContactFromEverything_caisse:
    path:     /ajax/getContactFromEverything
    defaults: { _controller: ImerirNoyauBundle:AjaxCaisse:rechercheClient }
    
imerir_noyau_ajax_getMoyenPaiement_caisse:
    path:     /ajax/getMoyenPaiement
    defaults: { _controller: ImerirNoyauBundle:AjaxCaisse:getMoyenPaiement }     
    
imerir_noyau_check:
    path:     /check_login/
    defaults: { _controller: ImerirNoyauBundle:Default:checkLogin }
    
imerir_noyau_caisse_save:
    path:     /enregistreAchat
    defaults: { _controller: ImerirNoyauBundle:Caisse:saveCaisse }

imerir_noyau_adresse_ajout:
    path: /adresse/ajout
    defaults: { _controller: ImerirNoyauBundle:Adresse:ajoutAdresse }