imerir_noyau_homepage:
    path:     /login/
    defaults: { _controller: ImerirNoyauBundle:Default:authentification }
    
imerir_noyau_index:
    path:     /index/
    defaults: { _controller: ImerirNoyauBundle:Default:getindex }