imerir_produit_modif_attributs:
    path:     /produits/attribut
    defaults: { _controller: ImerirProduitBundle:Attribut:modifAttribut }

imerir_produit_save_attributs:
    path:     /produits/attribut/save
    defaults: { _controller: ImerirProduitBundle:Attribut:saveAttribut }

imerir_produit_creation_produit:
    path:     /produits/creation
    defaults: { _controller: ImerirProduitBundle:Default:ajoutProduit }

imerir_produit_validation_creation_produit:
    path:     /produits/creation/validation
    defaults: { _controller: ImerirProduitBundle:Default:execAjoutProduit }

imerir_produit_modification_produit:
    path:     /produits/modification
    defaults: { _controller: ImerirProduitBundle:Default:modifProduit }

imerir_produit_validation_modification_produit:
    path:     /produits/modification/validation
    defaults: { _controller: ImerirProduitBundle:Default:execModifProduit }

imerir_produit_creation_ligne_produit:
    path:     /ligne_produits/creation
    defaults: { _controller: ImerirProduitBundle:LigneProduit:ajoutLigneProduit }

imerir_produit_validation_creation_ligne_produit:
    path:     /ligne_produits/creation/validation
    defaults: { _controller: ImerirProduitBundle:LigneProduit:execAjoutLigneProduit }

imerir_produit_modification_ligne_produit:
    path:     /ligne_produits/modification
    defaults: { _controller: ImerirProduitBundle:LigneProduit:modifLigneProduit }

imerir_produit_validation_modification_ligne_produit:
    path:     /ligne_produits/modification/validation
    defaults: { _controller: ImerirProduitBundle:LigneProduit:execModifLigneProduit }