imerir_produit_modif_attributs:
    path:     /produits/attribut
    defaults: { _controller: ImerirProduitBundle:Attribut:modifAttribut }

imerir_produit_save_attributs:
    path:     /produits/attribut/save
    defaults: { _controller: ImerirProduitBundle:Attribut:saveAttribut }

imerir_produit_creation_produit:
    path:     /produits/creation
    defaults: { _controller: ImerirProduitBundle:Default:creerProduit }
