imerir_produit_modif_attributs:
    path:     /produits/attribut
    defaults: { _controller: ImerirProduitBundle:Attribut:modifAttribut }

imerir_produit_save_attributs:
    path:     /produits/attribut/save
    defaults: { _controller: ImerirProduitBundle:Attribut:saveAttribut }

imerir_produit_supprimer_attributs:
    path:     /produits/attribut/supprimer
    defaults: { _controller: ImerirProduitBundle:Attribut:supprimerAttribut }

imerir_produit_creation_produit:
    path:     /produits/creation
    defaults: { _controller: ImerirProduitBundle:Default:ajoutProduit }

imerir_produit_validation_creation_produit:
    path:     /produits/creation/validation
    defaults: { _controller: ImerirProduitBundle:Default:execAjoutProduit }

imerir_produit_modification_produit:
    path:     /produits/modification
    defaults: { _controller: ImerirProduitBundle:Default:modifProduit }

imerir_produit_validation_modification_produit:
    path:     /produits/modification/validation
    defaults: { _controller: ImerirProduitBundle:Default:execModifProduit }

imerir_produit_creation_ligne_produit:
    path:     /ligne_produits/creation
    defaults: { _controller: ImerirProduitBundle:LigneProduit:ajoutLigneProduit }
    
imerir_produit_suppression_ligne_produit:
    path:     /ligne_produits/suppression
    defaults: { _controller: ImerirProduitBundle:LigneProduit:execSupprLigneProduit }    

imerir_produit_validation_creation_ligne_produit:
    path:     /ligne_produits/creation/validation
    defaults: { _controller: ImerirProduitBundle:LigneProduit:execAjoutLigneProduit }

imerir_produit_modification_ligne_produit:
    path:     /ligne_produits/modification
    defaults: { _controller: ImerirProduitBundle:LigneProduit:modifLigneProduit }

imerir_produit_validation_modification_ligne_produit:
    path:     /ligne_produits/modification/validation
    defaults: { _controller: ImerirProduitBundle:LigneProduit:execModifLigneProduit }
    
imerir_produit_article:
    path:     /article
    defaults: { _controller: ImerirProduitBundle:Article:modifArticle }
    
imerir_produit_article_save:
    path:     /article/save
    defaults: { _controller: ImerirProduitBundle:Article:saveArticle }

imerir_produit_article_supprimer:
    path:     /article/supprimer
    defaults: { _controller: ImerirProduitBundle:Article:supprimerArticle }
    
imerir_produit_code_barre:
    path:     /code_barre
    defaults: { _controller: ImerirProduitBundle:CodeBarre:index }

imerir_reception_article:
    path:   /article/reception
    defaults: { _controller: ImerirProduitBundle:ReceptionCommande:ajoutReception }

imerir_reception_article_saisie:
    path:   /article/reception/saisie
    defaults: { _controller: ImerirProduitBundle:ReceptionCommande:saisieReception }

imerir_reception_article_saisie_validation:
    path:   /article/reception/saisie/validation
    defaults: { _controller: ImerirProduitBundle:ReceptionCommande:execSaisieReception }