imerir_vente_stats:
    path:     /vente/stats
    defaults: { _controller: ImerirVenteBundle:Stats:index }

imerir_vente_stats_top_vente:
    path:     /vente/stats/top
    defaults: { _controller: ImerirVenteBundle:Stats:topVente }
    
imerir_vente_facture:
    path:     /vente/facture
    defaults: { _controller: ImerirVenteBundle:Facture:index }

imerir_vente_facture_detail:
    path:     /vente/facture/detail
    defaults: { _controller: ImerirVenteBundle:Facture:factureDetailFromLigneFacture }
    
imerir_vente_creation_moyen_paiement:
    path:     /vente/creation/moyen_paiement
    defaults: { _controller: ImerirVenteBundle:MoyenPaiement:index }
    
imerir_vente_afficher_modification_moyen_paiement:
    path:     /vente/afficher/modification/moyen_paiement
    defaults: { _controller: ImerirVenteBundle:MoyenPaiement:afficherEnModificationMoyenPaiement }
    
imerir_vente_modification_moyen_paiement:
    path:     /vente/modification/moyen_paiement
    defaults: { _controller: ImerirVenteBundle:MoyenPaiement:modificationMoyenPaiement }
    
imerir_vente_supprimer_moyen_paiement:
    path:     /vente/supprimer/moyen_paiement
    defaults: { _controller: ImerirVenteBundle:MoyenPaiement:supprimerMoyenPaiement }
    
imerir_vente_retour_client:
    path:     /vente/retour_client
    defaults: { _controller: ImerirVenteBundle:RetourClient:faireRetourClient }

imerir_vente_retour_client_detail:
    path:     /vente/retour_client_details
    defaults: { _controller: ImerirVenteBundle:RetourClient:faireRetourClientDetails }

imerir_vente_valider_retour_client:
    path:     /vente/retour_client/valid
    defaults: { _controller: ImerirVenteBundle:RetourClient:validerRetourClient }