imerir_vente_stats:
    path:     /vente/stats
    defaults: { _controller: ImerirVenteBundle:Stats:index }

imerir_vente_stats_top_vente:
    path:     /vente/stats/top
    defaults: { _controller: ImerirVenteBundle:Stats:topVente }
    
imerir_vente_facture:
    path:     /vente/facture
    defaults: { _controller: ImerirVenteBundle:Facture:index }

imerir_vente_facture_detail:
    path:     /vente/facture/detail
    defaults: { _controller: ImerirVenteBundle:Facture:factureDetailFromLigneFacture }